- name: Personal repositories
  hosts: local
  tags: personal

  tasks:
    - name: Clone my dotfiles
      tags: dotfiles
      ansible.builtin.git:
        repo: "git@github.com:{{ github_user }}/dotfiles.git"
        dest: "~/dotfiles"
        update: true

    - name: Install stow
      ansible.builtin.homebrew:
        name: stow
        state: present

    - name: Stow my dotfiles (no_yandex)
      shell: |
        # exit immediately if command exits with non-zero status
        set -e 
        cd {{ lookup('env', 'HOME') }}/dotfiles
        make backup && true
        make macbook

    - name: Check in ~/.config/nvim already exists
      stat:
        path: "~/.config/nvim"
      register: neovim_configuration

    - name: Clone my NeoVim config
      tags: 
        - dotfiles
      ansible.builtin.git:
        repo: "git@github.com:{{ github_user }}/nvim-config.git"
        dest: "~/.config/nvim"
      when: not neovim_configuration.stat.exists

    - name: Create Obsidian vault directory
      tags:
        - obsidian
      file:
        path: "{{ lookup('env', 'HOME') }}/Documents/ObsidianVault"
        state: directory
        mode: "0755"

    - name: Clone Obsidian worknotes
      tags:
        - obsidian
        - yandex
      ansible.builtin.git:
        repo: git@github.com:{{ github_user }}/Work.Yandex.git
        dest: "~/Documents/ObsidianVault/WorkYandex"
