- name: Initial play
  hosts: local
  tags: mac
  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Install git
      ansible.builtin.homebrew:
        name: git
        state: present

    - name: Install PostgreSQL 16
      ansible.builtin.homebrew:
        name: postgresql@16
        state: present

    - name: Install Obsidian
      tags: productivity
      ansible.builtin.homebrew:
        name: obsidian
        state: present

    - name: Tap MongoDB Homebrew repository
      tags: db
      ansible.builtin.homebrew_tap:
        name: mongodb/brew
        state: present
    
    - name: Install MongoDB Community Edition
      tags: db
      ansible.builtin.homebrew:
        name: mongodb-community
        state: present

    - name: Install Unnatural Scroll Wheels
      tags: mac
      ansible.builtin.homebrew:
        name: unnaturalscrollwheels
        state: present

- import_playbook: terminal_tools_playbook.yaml
- import_playbook: personal_repositories_playbook.yaml
- import_playbook: yandex_playbook.yaml
