- name: Initial play
  hosts: local
  tags: mac
  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Install git
      ansible.builtin.homebrew:
        name: git
        state: present

    - name: Install PostgreSQL 16
      tags: db
      ansible.builtin.homebrew:
        name: postgresql@16
        state: present

    - name: Install Obsidian
      tags: 
        - productivity
        - obsidian
      ansible.builtin.homebrew:
        name: obsidian
        state: present
      when: ansible_facts["system"] == "Darwin"

    - name: Tap nikitabobko/tap (Aerospace)
      homebrew_tap:
        name: nikitabobko/tap
        state: present
      when: ansible_facts["system"] == "Darwin"

    - name: Install tiling window manager (Aerospace)
      tags: productivity
      ansible.builtin.homebrew:
        name: nikitabobko/tap/aerospace
        state: present
        install_options: cask

    - name: Tap MongoDB Homebrew repository
      tags: db
      ansible.builtin.homebrew_tap:
        name: mongodb/brew
        state: present
    
    - name: Install MongoDB Community Edition
      tags: db
      ansible.builtin.homebrew:
        name: 
          - mongodb-community@4.4
          - mongosh
        state: present

    - name: Install Unnatural Scroll Wheels
      tags: mac
      ansible.builtin.homebrew:
        name: unnaturalscrollwheels
        state: present

    - name: Install Flameshot (screenshots) [allow in settings]
      tags: 
        - screenshots
        - productivity
      ansible.builtin.homebrew:
        name: flameshot
        state: present

- import_playbook: terminal_tools_playbook.yaml
- import_playbook: personal_repositories_playbook.yaml
- import_playbook: yandex_playbook.yaml
