- name: Initial play
  hosts: local
  tags: yandex
  tasks:

    - name: Add to brew yandex repository
      tags: 
        - arc
        - terminal
      ansible.builtin.homebrew_tap:
        name: yandex/arc 
        url: https://arc-vcs.yandex-team.ru/homebrew-tap
        state: present

    - name: Install Arc
      tags: 
        - arc
        - terminal
      ansible.builtin.homebrew:
        name: arc-launcher
        state: present

    - name: Update Arc
      tags: 
        - arc
        - terminal
      ansible.builtin.homebrew:
        name: arc-launcher
        state: present

    - name: Setup ssh keys access ("ssh-add")
      tags: 
        - arc
        - terminal
      shell: |
        ssh-add
        # arc token store
        
    - name: Check in ~/.config/nvim already exists
      stat:
        path: "~/.config/nvim"
      register: neovim_configuration

    - name: Checkout yandex branch of NeoVim config
      tags: 
        - yandex
      ansible.builtin.git:
        repo: "git@github.com:{{ github_user }}/nvim-config.git"
        dest: "~/.config/nvim"
        version: "yandex"
      when: neovim_configuration.stat.exists
      ignore_errors: true

